Efficient /state_ids
matrix-org/dendrite pull request #1922
Opened 2021-07-15 15:15 UTC by neilalexander

Beforehand, `/state_ids` was still pulling all of the state and auth events out of the database and unmarshalling them. This isn't really necessary because the `roomserver_events` table already knows both the event ID and the auth event NIDs, so we can look those up instead. This adds the necessary roomserver query shape to do just that.

2021-07-15 16:06 UTC, kegsay requested changes
It isn't returning the auth chain.

2021-07-15 16:06 UTC, kegsay commented on roomserver/api/query.go
> +	AuthChainEvents []string `json:"auth_chain_event_ids"`
These aren't events, they are event IDs. `AuthChainEventIDs` and `StateEventIDs` please.

2021-07-15 16:06 UTC, kegsay commented on roomserver/internal/query/query.go
> +		response.AuthChainEvents = append(response.AuthChainEvents, eventID)
These are just the auth events for the state events, not the auth chain.

2021-07-15 16:06 UTC, kegsay commented on roomserver/storage/sqlite3/events_table.go
> +		//{&s.bulkSelectEventAuthEventNIDsStmt, bulkSelectEventAuthEventNIDsSQL},
Spurious, please remove

2021-07-29 17:52 UTC, Devkey19 commented
Bug

2021-11-02 16:46 UTC, neilalexander commented
Stale.

2021-11-02 16:46 UTC, closed without merging