Add canonical alias support
matrix-org/dendrite pull request #2236
Opened 2022-03-01 13:21 UTC by S7evinK

For the changes in [roomserver/internal/alias.go](https://github.com/matrix-org/dendrite/compare/s7evink/canonicalalias?expand=1#diff-d96a304ebb23d290cee289680b2d30cb810a7af62a7fe42395ff2b7e3cdf6f92), I'm not sure if that's the correct thing to do.

2022-03-01 13:39 UTC, neilalexander requested changes

2022-03-01 13:39 UTC, neilalexander commented on roomserver/internal/alias.go
> +			StateEventIDs: stateEventIDs,
It's best not to specify `StateEventIDs` and `HasState` here — we only use those if we want to force the roomserver to create a new state snapshot, which isn't necessary in this case.

This means we should be able to remove all of the `r.QueryLatestEventsAndState` bit.

2022-03-01 13:39 UTC, neilalexander commented on roomserver/internal/alias.go
> +	if err != nil && err != sql.ErrNoRows {
There's no case for if the error is `sql.ErrNoRows` — should there be?

2022-03-04 11:12 UTC, neilalexander approved these changes

2022-03-07 09:37 UTC, merged

2022-03-26 07:57 UTC, NickCao commented on clientapi/routing/sendevent.go
> +		if aliasReq.Alias != "" && found < len(requestAliases) {
I think the check here is too strict. Consider the following usecase: we have a room federated between example.com and example.org, a user from example.com adds a canonical alias to the room, and then user b from example.org tries to add another alias, this event would be rejected. As local alias are not federated per https://spec.matrix.org/v1.2/client-server-api/#room-aliases. `GetAliasesForRoomID` request to example.org would not be able to list the alias set on example.com. I think the correct way to check this is to go through the full alias resolution process to make sure all the aliases in the event are resolved to the room in question.