Added Landing Page
matrix-org/dendrite pull request #2885
Opened 2022-11-18 21:54 UTC by LukasLJL

I have added/copied a landing page like Synpase does.
Recently I have installed Dendrite and was wondering why it´s not working. After some troubleshooting I figured out there is no landing page like synpase has, so the Server was running just fine. 

Hopefuly this PR can fix this problem and may help other users who run into this issue.
I have not written any unit tests, because it´s just a simple landing page with a redirect to a static site.

### Pull Request Checklist

* [x] I have added Go unit tests or [Complement integration tests](https://github.com/matrix-org/complement) for this PR _or_ I have justified why this PR doesn't need tests
* [x] Pull request includes a [sign off below using a legally identifiable name](https://matrix-org.github.io/dendrite/development/contributing#sign-off) _or_ I have already signed off privately

Signed-off-by: `Lukas Huida<lukas@leucali.net>`

2022-12-05 12:43 UTC, kegsay commented
This needs tests to ensure the routing is correct.

2022-12-07 14:06 UTC, kegsay requested changes
Needs tests to make sure routing is working correctly in monolith mode at the very least. Otherwise LGTM!

2022-12-08 08:35 UTC, LukasLJL commented
Thanks for the reply, could you give me a hint where I can add the test? Are there any example?

2022-12-08 10:15 UTC, kegsay commented
There aren't as there hasn't been anything like this before. You need a `setup.Monolith` and a `base.Dendrite` and to glue them together similar to https://github.com/matrix-org/dendrite/blob/main/cmd/dendrite-monolith-server/main.go - then you can make a fake request with [httptest](https://pkg.go.dev/net/http/httptest#NewRequest) and pass it to the handler to ensure you get back the HTML page.

2022-12-23 10:02 UTC, S7evinK commented
We should probably also embed the html file and/or make it a template to include the actual Dendrite version.
Something like
```html
    <h1>It works! Dendrite {{ .dendriteVersion }} is running</h1>
```
would be great.

2023-01-26 14:56 UTC, kegsay approved these changes
Otherwise LGTM

2023-01-26 14:56 UTC, kegsay commented on setup/base/base.go
> +		http.Redirect(w, r, httputil.PublicStaticPath, http.StatusSeeOther)
`http.StatusFound` surely?

2023-01-26 14:56 UTC, kegsay commented on setup/base/base.go
> +			"Version": internal.VersionString(),
It seems inefficient to template this every time the client asks. Just do it once at startup and return those bytes?

2023-01-26 15:25 UTC, merged