Don't omit `pattern` key if empty.
matrix-org/dendrite pull request #2891
Opened 2022-11-27 15:30 UTC by webzwo0i

This is needed to match state events with an empty string value. Fixes #2882

Feel free to dismiss this PR in case you think that clients should interpret a missing pattern key in state event conditions as if the pattern would be `*`. However, for a lot of state events, this would also match events that have an arbitrary value, not only those that have `pattern: ''`` (empty string).

2022-11-28 10:00 UTC, neilalexander commented
Looking at [the spec](https://spec.matrix.org/v1.5/client-server-api/#push-rules-events), `pattern` is not a "Required" field, which makes me think Fluffychat should be able to cope with it not being present and do the right thing.

2022-11-28 10:38 UTC, spaetz commented
The spec continues to state:

`pattern | string | Required for event_match conditions. The glob-style pattern to match against.`

So, pattern is required in the case of event_match conditions.

The dendrite code base recognizes that on line 15 of conditions.go:

```
	// Pattern indicates the value pattern that must match. Required
	// for EventMatchCondition.
	Pattern string `json:"pattern"`
```

So, we need to make sure that "pattern" is included ONLY when we have a case of
 `EventMatchCondition ConditionKind = "event_match"`.

2022-12-05 12:47 UTC, kegsay commented
What does Synapse do here?

2022-12-07 14:13 UTC, kegsay requested changes
Needs unit tests, and confirmation that this is right behaviour (what does Synapse do?) Also, we require sign-off.

2022-12-20 14:34 UTC, S7evinK commented
Closing in favor of https://github.com/matrix-org/dendrite/pull/2918

2022-12-20 14:34 UTC, closed without merging